# 2 预备知识
> 由于数据预处理暂时用不到，所以暂不涉及。

## 2.1 数据操作

In [2]:
# 创建与查看
import torch

# 1.1 创建一个从 0 到 11 的一维长向量
x = torch.arange(12)
print(f"原始向量: {x}")

# 1.2 查看张量的形状
print(f"形状: {x.shape}")

# 1.3 查看张量中元素的总数
print(f"元素总数: {x.numel()}")

# 1.4 改变形状 (Reshape)
# 注意：reshape 不改变数据，只改变读取方式
X = x.reshape(3, 4)
print(f"改变形状为 3x4:\n{X}")

# 1.5 特殊初始化
print("全 0:\n", torch.zeros((2, 3, 4))) # 括号里是形状
print("全 1:\n", torch.ones((2, 3)))
print("随机数 (标准正态分布):\n", torch.randn(3, 4))


原始向量: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
形状: torch.Size([12])
元素总数: 12
改变形状为 3x4:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
全 0:
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
全 1:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
随机数 (标准正态分布):
 tensor([[ 1.2986,  0.0411,  2.0329,  1.7145],
        [-0.3265,  1.6265, -0.4411,  1.1239],
        [-0.9739,  1.0434,  1.4065, -0.4151]])


In [3]:
# 广播机制
a = torch.arange(3).reshape((3, 1)) # 3行1列
b = torch.arange(2).reshape((1, 2)) # 1行2列

print("a:\n", a)
print("b:\n", b)

# 它们相加时，a 会复制成 3x2，b 会复制成 3x2
print("a + b:\n", a + b)

a:
 tensor([[0],
        [1],
        [2]])
b:
 tensor([[0, 1]])
a + b:
 tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [4]:
# 切片与索引
X = torch.arange(12).reshape(3, 4)
print("原矩阵:\n", X)

# 取最后一行
print("最后一行:", X[-1])

# 取第1行到第2行，且列全部都要
print("前两行:\n", X[0:2, :])

# 修改特定区域
X[0:2, :] = 12
print("修改后的 X:\n", X)

# 取最后一列
print("最后一列:", X[:, -1])

原矩阵:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
最后一行: tensor([ 8,  9, 10, 11])
前两行:
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
修改后的 X:
 tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])
最后一列: tensor([12, 12, 11])


In [5]:
# 原地更新数据
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])

before = id(y) # 查看 y 的内存地址
y = y + x
print(id(y) == before) # False, 地址变了

# 正确做法：使用 [:] 或 +=
# 切片 或者 自增
z = torch.tensor([3, 4])
before_z = id(z)
z += x  # 或者 z[:] = z + x
print(id(z) == before_z) # True, 地址没变，节省内存


False
True


In [6]:
# 2.1 综合训练
# 形状挑战
A = torch.randn(3, 5)
print(A)
A = A.T
print(A)

# 广播挑战
X = torch.randn(3, 1)
Y = torch.randn(1, 5)
print("X+Y 的形状是:\n", (X+Y).shape)

# 索引挑战
a = torch.ones(4, 4)
a[1:3, 1:3] = 0
print("修改后的 a 为:\n", a)

# 硬件挑战
device = torch.device("cuda")
a_gpu = a.to(device)
print("a 现在的运行设备为:\n", a_gpu.device)

tensor([[ 0.0274, -0.8460,  0.8239,  0.6913,  0.4143],
        [-1.7157, -1.8185, -0.0393, -0.7901,  0.7683],
        [-1.4398,  0.4515, -0.6884, -0.2056, -1.8657]])
tensor([[ 0.0274, -1.7157, -1.4398],
        [-0.8460, -1.8185,  0.4515],
        [ 0.8239, -0.0393, -0.6884],
        [ 0.6913, -0.7901, -0.2056],
        [ 0.4143,  0.7683, -1.8657]])
X+Y 的形状是:
 torch.Size([3, 5])
修改后的 a 为:
 tensor([[1., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.]])
a 现在的运行设备为:
 cuda:0


## 2.3 线性代数

In [7]:
# 基础运算：标量、向量、矩阵
import torch

# 标量相加
a = torch.tensor(3.0)
b = torch.tensor(2.0)
print(a + b, a * b, a / b, a**b)

# 向量长度(L2 范数)
x = torch.arange(4, dtype=torch.float32)
print("向量 x:", x)
print("向量长度:", torch.norm(x))

tensor(5.) tensor(6.) tensor(1.5000) tensor(9.)
向量 x: tensor([0., 1., 2., 3.])
向量长度: tensor(3.7417)


In [8]:
# 矩阵乘法
A = torch.ones(2, 3)
B = torch.ones(3, 4)

# C = A * B # * 表示按元素乘法，两个矩阵形状必须一样。
D = torch.mm(A, B) # 或者 A@B
print("矩阵乘法结果形状:", D.shape)

矩阵乘法结果形状: torch.Size([2, 4])


In [9]:
# 降维求和
X = torch.arange(12).reshape(3, 4)
print("原矩阵:\n", X)

# 全局求和
print("所有元素之和:", X.sum())

# 沿轴 0 求和（把行压缩，最后仅剩下列）
print("沿轴 0 求和:", X.sum(axis=0))

# 沿轴 1 求和（把列压缩，最后仅剩下行）
print("沿轴 1 求和:", X.sum(axis=1))

原矩阵:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
所有元素之和: tensor(66)
沿轴 0 求和: tensor([12, 15, 18, 21])
沿轴 1 求和: tensor([ 6, 22, 38])


In [ ]:
# 范数：限制模型参数，防止过拟合。
# 假设这是神经元的权重向量
w = torch.tensor([3.0, -4.0])

# L2 范数（欧几里得范数）：平方和开根号
# 代表向量在空间里的物理长度
l2 = torch.norm(w)
print(f"L2 范数(长度): {l2}")

# L1 范数：绝对值之和
# 代表向量的“绝对能量”总和
l1 = torch.abs(w).sum()
print(f"L1 范数(能量): {l1}")

# 矩阵的 Frobenius 范数：矩阵版的 L2 范数
A = torch.ones(2, 2)
print(f"矩阵 A 的 Frobenius 范数: {torch.norm(A)}")

L2 范数(长度): 5.0
L1 范数(能量): 7.0
矩阵 A 的 Frobenius 范数: 2.0


In [19]:
# 点积 vs 矩阵乘法
# 点积 (torch.dot)：两个向量（1D）的加权和。
# 矩阵-向量积 (torch.mv)：矩阵对向量进行转换。
# 矩阵乘法 (torch.mm)：空间对空间的转换。

# 向量 x
x = torch.tensor([1.0, 2.0])

# 矩阵 A：想象它是一个“空间变换器”
# 这个 A 会把 x 轴放大 2 倍，y 轴缩小为 0.5 倍
A = torch.tensor([[2.0, 0.0], 
                  [0.0, 0.5]])

# 矩阵向量积
y = torch.mv(A, x)
print(f"原始向量: {x}")
print(f"变换后的向量: {y}")

原始向量: tensor([1., 2.])
变换后的向量: tensor([2., 1.])


In [ ]:
# 大数定律
from torch.distributions import multinomial

# 定义每个点数的概率为 1/6
probabilities = torch.ones([6]) / 6

# 抽样 1000 次。multinomial 是多项式分布抽样
# 结果 counts 是每个点数出现的次数
counts = multinomial.Multinomial(1000, probabilities).sample()
print(f"1000 次实验中，各点数出现次数: {counts}")
print(f"实际频率: {counts / 1000}")

1000 次实验中，各点数出现次数: tensor([175., 187., 164., 171., 146., 157.])
实际频率: tensor([0.1750, 0.1870, 0.1640, 0.1710, 0.1460, 0.1570])


In [22]:
# 随机性
# 定义分布(抽奖箱)
p = torch.ones([6]) / 6
dist = multinomial.Multinomial(1000, p)

# 第一次抽样
draw1 = dist.sample()
print(f"第一次结果: {draw1}")

# 第二次抽样
draw2 = dist.sample()
print(f"第二次结果: {draw2}")

# 验证：两次结果虽然不一样，但总和都是 1000
print(f"总和: {draw1.sum()}, {draw2.sum()}")

第一次结果: tensor([167., 179., 171., 161., 173., 149.])
第二次结果: tensor([163., 182., 155., 177., 158., 165.])
总和: 1000.0, 1000.0


## 2.5 自动微分

In [11]:
# 标准的求导过程
# 1. 准备数据并开启梯度追踪
x = torch.arange(4.0, requires_grad=True)
print("x:", x)

# 2. 定义函数 (y = 2 * x的平方和)
y = 2 * torch.dot(x, x)
print("y:", y)

# 3. 反向传播
y.backward()

# 4. 查看结果(dy/dx = 4x)
print("x 的梯度:", x.grad)
print("验证是否等于 4x:", x.grad == 4 * x)


x: tensor([0., 1., 2., 3.], requires_grad=True)
y: tensor(28., grad_fn=<MulBackward0>)
x 的梯度: tensor([ 0.,  4.,  8., 12.])
验证是否等于 4x: tensor([True, True, True, True])


In [12]:
# 2.5 的补充知识点
x = torch.arange(4.0, requires_grad=True)
y = x * x

# A. 分离变量
u = y.detach() # u 与梯度信息无关，可以视为常量
z = u * x
z.sum().backward()
print(f"分离后的 x 梯度 (应该是 u 的值): {x.grad}") # 因为 u 被看作常数

# B. 清零对比
x.grad.zero_() # 先清零
y.sum().backward()
print(f"正常的 x 梯度 (应该是 2x): {x.grad}")

分离后的 x 梯度 (应该是 u 的值): tensor([0., 1., 4., 9.])
正常的 x 梯度 (应该是 2x): tensor([0., 2., 4., 6.])


In [13]:
# 2.3 & 2.5 综合实战
# 矩阵乘法挑战
A = torch.randn(5, 3)
B = torch.randn(3, 2)
C = A @ B
C_mean = C.mean()

print("C 各个元素的平均值为:", C_mean)

# 求和挑战
X = torch.randn(2, 5, 4)
print("沿轴 0 求和的形状:", X.sum(axis = 0).shape)
print("沿轴 1 求和的形状:", X.sum(axis = 1).shape)
print("沿轴 2 求和的形状:", X.sum(axis = 2).shape)

# 自动微分挑战
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = torch.prod(x)
y.backward()

print("x 的梯度:", x.grad)

C 各个元素的平均值为: tensor(0.0943)
沿轴 0 求和的形状: torch.Size([5, 4])
沿轴 1 求和的形状: torch.Size([2, 4])
沿轴 2 求和的形状: torch.Size([2, 5])
x 的梯度: tensor([6., 3., 2.])
